# Generated by Django 3.0.7 on 2023-04-12 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('escola', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='data_nascimento',
        ),
    ]
